# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Code Katas CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  project-build:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        java-version: [17, 18]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Download JDK ${{ matrix.java-version }}
        uses: sormuras/download-jdk@v1
        id: download-jdk
        with:
          feature: ${{ matrix.java-version }}
      - name: Set JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ steps.download-jdk.outputs.version }}
          distribution: jdkfile
          jdkFile: ${{ steps.download-jdk.outputs.file }}
      - name: JDK Version
        run: java --version
      - name: Enable Maven Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven
        run: mvn verify -DskipTests=true -Dmaven.javadoc.skip=true -B -V --no-transfer-progress
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS"
